baseURL: https://christiangitter.de
languageCode: de-de
title: christiangitter.de
paginate: 5
theme: github.com/adityatelange/hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

module:
  imports:
    path: github.com/adityatelange/hugo-PaperMod
    disabled: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Christian Gitter"
  description: "Es gibt Tage, da verspeist man den B채ren, und Tage, da wird man eben vom B채ren verspeist."
  author: ["Chris"]
  # author: ["Me", "You"] # multiple authors
  images: [] # ["<link or path of image for opengraph, twitter-cards>"]

  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  disableSpecial1stPost: false
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: ""
  #       icon: /apple-touch-icon.png
  #       iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Christian Gitter &ndash; Webentwickler"
    subtitle: "Es gibt Tage, da verspeist man den B채ren, und Tage, da wird man eben vom B채ren verspeist."
    imageUrl: "/avatar.jfif"
    imageWidth: 240
    imageHeight: 240
    imageTitle: Christian Gitter
    # buttons:
    #     - name: "Zum Blog"
    #       url: blog

  # home-info mode
  # homeInfoParams:
  #     Title: "Hi there \U0001F44B"
  #     Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/ChristianGitter/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/ChrisGitter/"

  #    analytics:
  #        google:
  #            SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# menu:
#     main:
#         - identifier: categories
#           name: categories
#           url: /categories/
#           weight: 10
#         - identifier: tags
#           name: tags
#           url: /tags/
#           weight: 20
# - identifier: example
#   name: example.org
#   url: https://example.org
#   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

# https://gohugo.io/about/hugo-and-gdpr/#disable-all-services
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
